version: "3"
services:
  fhirsecu:
    build: .
    container_name: fhirsecu
    restart: on-failure
    ports:
      - "8888:8080"
      - "8443:8443"
    volumes:
      - ./ssl:/usr/local/tomcat/ssl
      - ./server.xml:/usr/local/tomcat/conf/server.xml
            #- ./tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml
  hapi-fhir-mysql:
    image: mysql:latest
    container_name: hapi-fhir-mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'hapi'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'admin'
      MYSQL_ROOT_PASSWORD: 'admin'
    volumes:
      - hapi-fhir-mysql:/var/lib/mysql
volumes:
  hapi-fhir-mysql:

